version: '3'
services:
  builders_crm:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: builders/crm
    depends_on:  
      - db
    ports:
      - '8080:8080'
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - CRM_DATABASE_URL=db
      - CRM_DATABASE_USERNAME=sa
      - CRM_DATABASE_PASSWORD=1234
      - CRM_DATABASE_NAME=crmApi_db
      - CRM_DATABASE_PORT=8082
      - PORT=8080
  db:
    image: buildo/h2database
    ports:
      - '8082:8082'
    volumes:  
      - db-data:/var/lib/mysql
volumes:  
  db-data: